[theme]
base = "dark"
primaryColor = "#097e57ff"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#262730"
textColor = "#fafafa"

[server]
headless = false
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false